{{- if $.Values.salesforcePubSub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supaglue.componentname" (list . "salesforce-pub-sub") }}
  labels:
    app.kubernetes.io/name: {{ include "supaglue.name" . }}
    helm.sh/chart: {{ include "supaglue.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.salesforcePubSub.image.tag | replace "+" "_" }}
    app.kubernetes.io/component: salesforce-pub-sub
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.salesforcePubSub.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "supaglue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: salesforce-pub-sub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "supaglue.name" . }}
        helm.sh/chart: {{ include "supaglue.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.salesforcePubSub.image.tag | replace "+" "_" }}
        app.kubernetes.io/component: salesforce-pub-sub
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        {{- with .Values.salesforcePubSub.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.salesforcePubSub.metrics.annotations.enabled }}
        prometheus.io/job: {{ .Chart.Name }}-salesforce-pub-sub
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        {{- end }}
        {{- with .Values.salesforcePubSub.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ include "supaglue.serviceAccount" . }}
      initContainers:
        - name: wait-for-database
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ template "supaglue.databaseHost" . }} {{ template "supaglue.databasePort" $ }}; do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ $.Chart.Name }}-salesforce-pub-sub
          image: "{{ default "supaglue/salesforce-pub-sub" .Values.salesforcePubSub.image.repository }}:{{ default .Chart.AppVersion .Values.salesforcePubSub.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.salesforcePubSub.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            {{- with .Values.environment }}
            - name: SUPAGLUE_ENVIRONMENT
              value: {{ . }}
            {{- end }}
            - name: SUPAGLUE_LOG_LEVEL
              value: {{ .Values.salesforcePubSub.logLevel }}
            - name: SUPAGLUE_API_ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ .Values.secretKeys.dbEncryptionSecret }}
            - name: SUPAGLUE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" }}
                  key: {{ default "salesforce-pub-sub-database-url" .Values.secretKeys.salesforcePubSubDatabaseUrl }}
            - name: SVIX_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "supaglue.secretName" . }}
                  key: {{ default "svix-api-token" .Values.secretKeys.svixApiToken }}
            - name: SUPAGLUE_DEPLOYMENT_ID
              value: {{ include "supaglue.deploymentId" . }}
            {{- with .Values.salesforcePubSub.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            {{- if .Values.salesforcePubSub.additionalVolumeMounts }}
            {{- toYaml .Values.salesforcePubSub.additionalVolumeMounts | nindent 12}}
            {{- end }}
          resources:
            {{- toYaml .Values.salesforcePubSub.resources | nindent 12 }}
        {{- if .Values.salesforcePubSub.sidecarContainers }}
        {{- toYaml .Values.salesforcePubSub.sidecarContainers | nindent 8 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.salesforcePubSub.additionalVolumes }}
        {{- toYaml .Values.salesforcePubSub.additionalVolumes | nindent 8}}
        {{- end }}
      {{- with .Values.salesforcePubSub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.salesforcePubSub.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.salesforcePubSub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
